name: Sync Fork

on:
  schedule:
    - cron: '0 7 * * *' # scheduled at 07:00 UTC time every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: MungoMeng
          base: master
          head: master
